services:
  sharelatex:
    image: fred1653/sharelatex:0.2.0
    container_name: texdock-sharelatex
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:80"
    stop_grace_period: 60s
    environment:
      SHARELATEX_APP_NAME: TeXDock
      SHARELATEX_MONGO_URL: mongodb://mongo:27017/sharelatex
      SHARELATEX_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: "project_file,project_output_file"
      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "true"
    volumes:
      - sharelatex_data:/var/lib/overleaf
      - sharelatex_logs:/var/log/overleaf

  mongo:
    image: mongo:6.0
    container_name: texdock-mongo
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    extra_hosts:
      - mongo:127.0.0.1
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: texdock-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  sharelatex_data:
  sharelatex_logs:
  mongo_data:
  redis_data:
